### ISSUE TITLE
On first console run error (docker)

### ISSUE THREAD

**Issue by cr4zyrain** [netrunn3r/pytbull-ng#30]
`[root@localhost ~]# docker run --rm -it efigo/pytbull-ng -m victim`
`standard_init_linux.go:219: exec user process caused: no such file or directory`

**Comment by netrunn3r** [comment]
Problem was with wrong line ending in entrypoint.sh - it should be unix style (LF) but was windows-style (CRLF). I correct this in this repo and make new build in docker repo.

You should run `docker pull efigo/pytbull-ng` to get new version of pytbull-ng.
